DROP SCHEMA IF EXISTS types CASCADE;
DROP SCHEMA IF EXISTS book CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS sales CASCADE;

CREATE SCHEMA types;
CREATE SCHEMA book;
CREATE SCHEMA auth;
CREATE SCHEMA sales;

CREATE TYPE types.delivery_type AS ENUM ('STANDARD', 'EXPRESS', 'PICKUP');
CREATE TYPE types.order_status AS ENUM ('CREATED', 'CLAIMED', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'COMPLETED');

CREATE TYPE types.age_group AS ENUM ('CHILD', 'TEEN', 'ADULT', 'OTHER');
CREATE TYPE types.language as ENUM ('ENGLISH', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'UKRAINIAN', 'OTHER');

CREATE TABLE auth.users (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_public_id UNIQUE (public_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_name_min_length CHECK (LENGTH(name) > 1)
);

CREATE TABLE auth.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE auth.users_roles (
    user_id BIGINT,
    role_id BIGINT,
    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_users
        FOREIGN KEY (user_id)
        REFERENCES auth.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_users_roles_roles
        FOREIGN KEY (role_id)
        REFERENCES auth.roles (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE auth.clients (
    id BIGINT,
    balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT fk_clients_users
        FOREIGN KEY (id)
        REFERENCES auth.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT ck_clients_balance_min CHECK (balance >= 0.00)
);

CREATE TABLE auth.employees (
    id BIGINT,
    phone VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT fk_employees_users
        FOREIGN KEY (id)
        REFERENCES auth.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT uq_employees_phone UNIQUE (phone),
    CONSTRAINT ck_employees_birth_date_in_the_past CHECK (birth_date < CURRENT_DATE)
);

CREATE TABLE auth.admins (
    id BIGINT,
    CONSTRAINT pk_admins PRIMARY KEY (id),
    CONSTRAINT fk_admins_users
        FOREIGN KEY (id)
        REFERENCES auth.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE sales.shopping_carts (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    total_amount DECIMAL(19, 2) NOT NULL,
    client_id BIGINT NOT NULL,
    CONSTRAINT pk_shopping_carts PRIMARY KEY (id),
    CONSTRAINT uq_shopping_carts_public_id UNIQUE (public_id),
    CONSTRAINT ck_shopping_carts_total_amount_min CHECK (total_amount >= 0.00),
    CONSTRAINT fk_shopping_carts_clients
        FOREIGN KEY (client_id)
        REFERENCES auth.clients (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE book.books (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR(255) NOT NULL,
    age_group types.age_group NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    publication_date DATE NOT NULL,
    number_of_pages INTEGER NOT NULL,
    description TEXT NOT NULL,
    language types.language NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id),
    CONSTRAINT uq_books_public_id UNIQUE (public_id),
    CONSTRAINT ck_books_name_min_length CHECK (LENGTH(name) > 1),
    CONSTRAINT ck_books_price_min CHECK (price >= 0.00),
    CONSTRAINT ck_books_number_of_pages_min CHECK (number_of_pages >= 0),
    CONSTRAINT ck_books_publication_date_past CHECK (publication_date <= CURRENT_DATE)
);

CREATE TABLE book.characteristics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    CONSTRAINT pk_characteristics PRIMARY KEY (id),
    CONSTRAINT uq_characteristics_name UNIQUE (name),
    CONSTRAINT ck_characteristics_name_min_length CHECK (LENGTH(name) > 1),
    CONSTRAINT uq_characteristics_slug UNIQUE (slug),
    CONSTRAINT ck_characteristics_slug_min_length CHECK (LENGTH(slug) > 1)
);

CREATE TABLE book.books_characteristics (
    book_id BIGINT,
    characteristic_id BIGINT,
    CONSTRAINT pk_books_characteristics PRIMARY KEY (book_id, characteristic_id),
    CONSTRAINT fk_books_characteristics_books
        FOREIGN KEY (book_id)
        REFERENCES book.books (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_books_characteristics_characteristics
        FOREIGN KEY (characteristic_id)
        REFERENCES book.characteristics (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE book.authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    bio TEXT,
    birth_date DATE,
    CONSTRAINT pk_authors PRIMARY KEY (id),
    CONSTRAINT uq_authors_name UNIQUE (name),
    CONSTRAINT ck_authors_name_min_length CHECK (LENGTH(name) > 1),
    CONSTRAINT uq_authors_slug UNIQUE (slug),
    CONSTRAINT ck_authors_slug_min_length CHECK (LENGTH(slug) > 1),
    CONSTRAINT ck_authors_birth_date_in_the_past CHECK (birth_date < CURRENT_DATE)
);

CREATE TABLE book.books_authors (
    book_id BIGINT,
    author_id BIGINT,
    CONSTRAINT pk_books_authors PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_books_authors_books
        FOREIGN KEY (book_id)
        REFERENCES book.books (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_books_authors_authors
        FOREIGN KEY (author_id)
        REFERENCES book.authors (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE book.genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    slug VARCHAR(50) NOT NULL,
    description TEXT,
    CONSTRAINT pk_genres PRIMARY KEY (id),
    CONSTRAINT uq_genres_name UNIQUE (name),
    CONSTRAINT ck_genres_name_min_length CHECK (LENGTH(name) > 1),
    CONSTRAINT uq_genres_slug UNIQUE (slug),
    CONSTRAINT ck_genres_slug_min_length CHECK (LENGTH(slug) > 1)
);

CREATE TABLE book.books_genres (
  book_id BIGINT,
  genre_id BIGINT,
  CONSTRAINT pk_books_genres PRIMARY KEY (book_id, genre_id),
  CONSTRAINT fk_books_genres_books
      FOREIGN KEY (book_id)
      REFERENCES book.books (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT fk_books_genres_genres
      FOREIGN KEY (genre_id)
      REFERENCES book.genres (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE sales.shopping_cart_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    cart_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_add DECIMAL(19, 2) NOT NULL,
    subtotal DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_shopping_cart_items PRIMARY KEY (id),
    CONSTRAINT uq_shopping_cart_items_public_id UNIQUE (public_id),
    CONSTRAINT fk_shopping_cart_items_shopping_carts
        FOREIGN KEY (cart_id)
        REFERENCES sales.shopping_carts (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_shopping_cart_items_books
        FOREIGN KEY (book_id)
        REFERENCES book.books (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT ck_shopping_cart_items_quantity_min CHECK (quantity >= 0),
    CONSTRAINT ck_shopping_cart_items_price_at_add_min CHECK (price_at_add >= 0.00),
    CONSTRAINT ck_shopping_cart_items_subtotal_min CHECK (subtotal >= 0.00)
);

CREATE TABLE sales.orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    client_id BIGINT,
    employee_id BIGINT,
    order_date TIMESTAMPTZ NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    delivery_type types.delivery_type NOT NULL,
    delivery_address VARCHAR(255),
    comment TEXT,
    status types.order_status NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_public_id UNIQUE (public_id),
    CONSTRAINT fk_orders_clients
        FOREIGN KEY (client_id)
        REFERENCES auth.clients (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id)
        REFERENCES auth.employees (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT ck_orders_order_date_in_the_past CHECK (order_date <= NOW())
);

CREATE TABLE sales.order_cancellations (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    cancelled_by BIGINT,
    order_id BIGINT NOT NULL,
    reason TEXT,
    cancelled_at TIMESTAMPTZ,
    CONSTRAINT pk_order_cancellations PRIMARY KEY (id),
    CONSTRAINT fk_orders_cancelled_by
        FOREIGN KEY (cancelled_by)
        REFERENCES auth.employees (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT uq_order_cancellations_order_id UNIQUE (order_id),
    CONSTRAINT fk_order_cancellations_orders
        FOREIGN KEY (order_id)
        REFERENCES sales.orders (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT ck_order_cancellations_cancelled_at_in_the_past CHECK (cancelled_at <= NOW())
);

CREATE TABLE sales.order_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    order_id BIGINT NOT NULL,
    book_public_id UUID NOT NULL,
    book_name VARCHAR(255) NOT NULL,
    price_at_purchase DECIMAL(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_orders
        FOREIGN KEY (order_id)
        REFERENCES sales.orders (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT ck_order_items_book_name_min_length CHECK (LENGTH(book_name) > 1),
    CONSTRAINT ck_order_items_price_at_purchase_min CHECK (price_at_purchase >= 0.00),
    CONSTRAINT ck_order_items_quantity_min CHECK (quantity >= 0),
    CONSTRAINT ck_order_items_subtotal_min CHECK (subtotal >= 0.00)
);
