DROP TABLE IF EXISTS public.users_roles;
DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.order_items;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.shopping_cart_items;
DROP TABLE IF EXISTS public.books;
DROP TABLE IF EXISTS public.shopping_carts;
DROP TABLE IF EXISTS public.clients;
DROP TABLE IF EXISTS public.employees;
DROP TABLE IF EXISTS public.admins;
DROP TABLE IF EXISTS public.users;

DROP TYPE IF EXISTS types.delivery_type;
DROP TYPE IF EXISTS types.order_status;
DROP TYPE IF EXISTS types.age_group;
DROP TYPE IF EXISTS types.language;

DROP SCHEMA IF EXISTS types;

CREATE SCHEMA types;

CREATE TYPE types.delivery_type AS ENUM ('STANDARD', 'EXPRESS', 'PICKUP');
CREATE TYPE types.order_status AS ENUM ('CREATED', 'CLAIMED', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'COMPLETED');

CREATE TYPE types.age_group AS ENUM ('CHILD', 'TEEN', 'ADULT', 'OTHER');
CREATE TYPE types.language as ENUM ('ENGLISH', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'UKRAINIAN', 'OTHER');

CREATE TABLE public.users (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_public_id UNIQUE (public_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_name_min_length CHECK (LENGTH(name) > 1)
);

CREATE TABLE public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE public.users_roles (
    user_id BIGINT,
    role_id BIGINT,
    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_users
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_users_roles_roles
        FOREIGN KEY (role_id)
        REFERENCES public.roles (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE public.clients (
    id BIGINT,
    balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT fk_clients_users
        FOREIGN KEY (id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE public.employees (
    id BIGINT,
    phone VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT fk_employees_users
        FOREIGN KEY (id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT uq_employees_phone UNIQUE (phone)
);

CREATE TABLE public.admins (
    id BIGINT,
    CONSTRAINT pk_admins PRIMARY KEY (id),
    CONSTRAINT fk_admins_users
        FOREIGN KEY (id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE public.shopping_carts (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    total_amount DECIMAL(19, 2) NOT NULL,
    client_id BIGINT NOT NULL,
    CONSTRAINT pk_shopping_carts PRIMARY KEY (id),
    CONSTRAINT uq_shopping_carts_public_id UNIQUE (public_id),
    CONSTRAINT fk_shopping_carts_clients
        FOREIGN KEY (client_id)
        REFERENCES public.clients (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE public.books (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL,
    age_group types.age_group NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    publication_date DATE NOT NULL,
    author VARCHAR(255) NOT NULL,
    number_of_pages INTEGER NOT NULL,
    characteristics TEXT NOT NULL,
    description TEXT NOT NULL,
    language types.language NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id),
    CONSTRAINT uq_books_public_id UNIQUE (public_id),
    CONSTRAINT ck_books_name_min_length CHECK (LENGTH(name) > 1),
    CONSTRAINT ck_books_publication_date_past CHECK (publication_date <= CURRENT_DATE)
);

CREATE TABLE public.shopping_cart_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    cart_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_add DECIMAL(19, 2) NOT NULL,
    subtotal DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_shopping_cart_items PRIMARY KEY (id),
    CONSTRAINT uq_shopping_cart_items_public_id UNIQUE (public_id),
    CONSTRAINT fk_shopping_cart_items_shopping_carts
        FOREIGN KEY (cart_id)
        REFERENCES public.shopping_carts (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_shopping_cart_items_books
        FOREIGN KEY (book_id)
        REFERENCES public.books (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE public.orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    public_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    client_id BIGINT,
    employee_id BIGINT,
    order_date TIMESTAMPTZ NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    delivery_type types.delivery_type NOT NULL,
    delivery_address VARCHAR(255),
    comment TEXT,
    status types.order_status NOT NULL,
    cancelled_by BIGINT,
    reason TEXT,
    cancelled_at TIMESTAMPTZ,
    version BIGINT NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_public_id UNIQUE (public_id),
    CONSTRAINT fk_orders_clients
        FOREIGN KEY (client_id)
        REFERENCES public.clients (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_orders_cancelled_by
        FOREIGN KEY (cancelled_by)
        REFERENCES public.employees (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE public.order_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    order_id BIGINT NOT NULL,
    book_public_id UUID NOT NULL,
    book_name VARCHAR(255) NOT NULL,
    price_at_purchase DECIMAL(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_orders
        FOREIGN KEY (order_id)
        REFERENCES public.orders (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
